import { Queue, Worker, type QueueOptions, type WorkerOptions } from 'bullmq';
import { env } from '../config/env.js';
import { findJob } from '../db/jobs.js';
import { runJob } from './job-runner.js';

const QUEUE_NAME = 'scrape-runs';

type Connection = QueueOptions['connection'];

function connection(): Connection {
  const url = new URL(env.redisUrl || 'redis://localhost:6379');
  return {
    host: url.hostname,
    port: Number(url.port || 6379),
    password: url.password || undefined,
  };
}

export type ScrapeJobData = {
  jobId: string;
  userId: string;
  /** Optional run id to attach to; generated by the runner otherwise. */
  runId?: string;
};

let queue: Queue<ScrapeJobData> | null = null;
let worker: Worker<ScrapeJobData> | null = null;

export function getQueue(): Queue<ScrapeJobData> {
  if (!queue) {
    queue = new Queue<ScrapeJobData>(QUEUE_NAME, {
      connection: connection(),
      defaultJobOptions: {
        removeOnComplete: { age: 24 * 3600, count: 1000 },
        removeOnFail: { age: 7 * 24 * 3600, count: 1000 },
        attempts: 1,
      },
    });
  }
  return queue;
}

export function startWorker(): Worker<ScrapeJobData> {
  if (worker) return worker;
  const opts: WorkerOptions = { connection: connection(), concurrency: 2 };
  worker = new Worker<ScrapeJobData>(
    QUEUE_NAME,
    async (job) => {
      const { jobId, userId, runId } = job.data;
      const row = await findJob(userId, jobId);
      if (!row) throw new Error(`Job ${jobId} not found for user ${userId}`);
      return runJob(row, runId);
    },
    opts,
  );
  worker.on('failed', (job, err) => {
    console.error('[queue] job failed', job?.id, err.message);
  });
  return worker;
}

export async function closeQueue(): Promise<void> {
  await Promise.allSettled([
    worker ? worker.close() : Promise.resolve(),
    queue ? queue.close() : Promise.resolve(),
  ]);
  worker = null;
  queue = null;
}

function repeatableKey(jobId: string): string {
  return `scrape-${jobId}`;
}

/** Ensure a repeatable entry exists for enabled+scheduled jobs. Removes any previous one first. */
export async function syncSchedule(args: {
  jobId: string;
  userId: string;
  enabled: boolean;
  schedule: string | null;
}): Promise<void> {
  const q = getQueue();
  // Remove any previous schedule for this job.
  const existing = await q.getJobSchedulers();
  for (const s of existing) {
    if (s.key === repeatableKey(args.jobId)) {
      await q.removeJobScheduler(s.key);
    }
  }
  if (args.enabled && args.schedule) {
    await q.upsertJobScheduler(
      repeatableKey(args.jobId),
      { pattern: args.schedule },
      {
        name: 'scheduled',
        data: { jobId: args.jobId, userId: args.userId },
      },
    );
  }
}

export async function enqueueNow(data: ScrapeJobData): Promise<void> {
  await getQueue().add('manual', data, { jobId: `manual-${data.jobId}-${Date.now()}` });
}
