import { Queue, Worker, type QueueOptions, type WorkerOptions } from 'bullmq';
import { env } from '../config/env.js';
import { findJob, listScheduledJobs } from '../db/jobs.js';
import { findOrCreateRunForQueueJob, findRun, findRunByQueueJobId } from '../db/runs.js';
import { runJob, type RunSummary } from './job-runner.js';
import { deliverForRun } from './webhooks.js';

const QUEUE_NAME = 'scrape-runs';

type Connection = QueueOptions['connection'];

function connection(): Connection {
  const url = new URL(env.redisUrl || 'redis://localhost:6379');
  return {
    host: url.hostname,
    port: Number(url.port || 6379),
    password: url.password || undefined,
  };
}

export type ScrapeJobData = {
  jobId: string;
  userId: string;
  /** Optional run id to attach to; generated by the runner otherwise. */
  runId?: string;
};

let queue: Queue<ScrapeJobData> | null = null;
let worker: Worker<ScrapeJobData> | null = null;

export function getQueue(): Queue<ScrapeJobData> {
  if (!queue) {
    queue = new Queue<ScrapeJobData>(QUEUE_NAME, {
      connection: connection(),
      defaultJobOptions: {
        removeOnComplete: { age: 24 * 3600, count: 1000 },
        removeOnFail: { age: 7 * 24 * 3600, count: 1000 },
        attempts: 1,
      },
    });
  }
  return queue;
}

export function startWorker(): Worker<ScrapeJobData> {
  if (worker) return worker;
  const opts: WorkerOptions = { connection: connection(), concurrency: 2 };
  worker = new Worker<ScrapeJobData>(
    QUEUE_NAME,
    async (job) => {
      const { jobId, userId, runId } = job.data;
      const row = await findJob(userId, jobId);
      if (!row) throw new Error(`Job ${jobId} not found for user ${userId}`);

      // Run identity. Manual triggers pass runId in the payload; scheduled
      // jobs don't, so we key the run on the BullMQ job id. A stalled-job
      // retry (BullMQ re-queues a job whose worker lost its lock — i.e. the
      // original attempt is presumed dead) carries the same BullMQ id.
      //
      //   - already terminal → skip re-running, but still fall through to
      //     webhook delivery below (a crash between run-finalize and webhook
      //     send would otherwise drop the webhook permanently).
      //   - non-terminal / absent → find-or-create the run (atomic via the
      //     partial UNIQUE index, so concurrent processing can't duplicate the
      //     row) and run it. Re-running a non-terminal run is the intended
      //     crash-recovery behaviour; updateRun is idempotent on the row.
      let effectiveRunId = runId;
      let summary: RunSummary;
      let alreadyTerminal = false;

      if (!effectiveRunId && job.id) {
        const existing = await findRunByQueueJobId(String(job.id));
        if (existing && (existing.status === 'completed' || existing.status === 'failed')) {
          alreadyTerminal = true;
          summary = {
            runId: existing.id,
            jobId: existing.job_id,
            status: existing.status,
            itemsExtracted: existing.items_extracted,
            tokensUsed: existing.tokens_used,
            error: existing.error_message ?? undefined,
            errorType: existing.error_type ?? undefined,
          };
        } else {
          const run = existing ?? (await findOrCreateRunForQueueJob(jobId, String(job.id)));
          effectiveRunId = run.id;
        }
      }

      if (!alreadyTerminal) {
        summary = await runJob(row, effectiveRunId);
      }

      // Webhook delivery is best-effort: failures are persisted on the run row
      // (webhook_status / webhook_last_error) but never bubble up to fail the
      // queue job. Skip if already delivered so a terminal-reattach retry
      // doesn't double-send; a previously *failed* delivery is retried.
      if (row.webhook_url && (summary!.status === 'completed' || summary!.status === 'failed')) {
        try {
          const runRow = await findRun(userId, summary!.runId);
          if (runRow && runRow.webhook_status !== 'success') {
            await deliverForRun({ job: row, userId, run: runRow });
          }
        } catch (err) {
          console.error('[webhook] delivery error', err);
        }
      }
      return summary!;
    },
    opts,
  );
  worker.on('failed', (job, err) => {
    console.error('[queue] job failed', job?.id, err.message);
  });
  return worker;
}

export async function closeQueue(): Promise<void> {
  await Promise.allSettled([
    worker ? worker.close() : Promise.resolve(),
    queue ? queue.close() : Promise.resolve(),
  ]);
  worker = null;
  queue = null;
}

function repeatableKey(jobId: string): string {
  return `scrape-${jobId}`;
}

/** Ensure a repeatable entry exists for enabled+scheduled jobs. Removes any previous one first. */
export async function syncSchedule(args: {
  jobId: string;
  userId: string;
  enabled: boolean;
  schedule: string | null;
}): Promise<void> {
  const q = getQueue();
  // Remove any previous schedule for this job.
  const existing = await q.getJobSchedulers();
  for (const s of existing) {
    if (s.key === repeatableKey(args.jobId)) {
      await q.removeJobScheduler(s.key);
    }
  }
  if (args.enabled && args.schedule) {
    await q.upsertJobScheduler(
      repeatableKey(args.jobId),
      { pattern: args.schedule },
      {
        name: 'scheduled',
        data: { jobId: args.jobId, userId: args.userId },
      },
    );
  }
}

export async function enqueueNow(data: ScrapeJobData): Promise<void> {
  await getQueue().add('manual', data, { jobId: `manual-${data.jobId}-${Date.now()}` });
}

/**
 * Reconcile BullMQ job schedulers against Postgres at boot. Redis is a
 * derived cache: if it was flushed, restored from an old snapshot, or simply
 * lost, every enabled+scheduled job in Postgres is re-upserted here, and any
 * `scrape-*` scheduler with no matching enabled job is removed. Without this,
 * Redis data loss silently kills all schedules while the UI still shows
 * `enabled = true`.
 *
 * Only keys with the `scrape-` prefix are touched, so an unrelated queue
 * sharing the Redis instance is left alone.
 */
export async function reconcileSchedules(): Promise<{ upserted: number; removed: number }> {
  const q = getQueue();
  const jobs = await listScheduledJobs();
  const wanted = new Set(jobs.map((j) => repeatableKey(j.id)));

  let removed = 0;
  const existing = await q.getJobSchedulers();
  for (const s of existing) {
    if (s.key && s.key.startsWith('scrape-') && !wanted.has(s.key)) {
      await q.removeJobScheduler(s.key);
      removed += 1;
    }
  }

  for (const j of jobs) {
    await q.upsertJobScheduler(
      repeatableKey(j.id),
      { pattern: j.schedule },
      { name: 'scheduled', data: { jobId: j.id, userId: j.user_id } },
    );
  }

  return { upserted: jobs.length, removed };
}
